---
title: "Management Scenarios"
---

Management Scenarios tab gives you the option to explore the potential affection of a set of marine economic
activities (i.e. wind farms, aquaculture plants, vessel routes and/or defence/military areas) in the study 
areas where the Ph.D. studies have been carried out. In this sense, you can select Santander Coast, North Sea, 
Irish Sea, Urdaibai Estuary and Cadiz Bay study areas. The affection in this Proof of Concept is based on the [Physical 
Accounts studies](https://docs.google.com/document/d/1qBrr96Hek-HVC-K4_4n9cyR9cEJ_d24o/edit#heading=h.i7jku579q3oc)
and the [Saltmarsh Evolution studies](https://www.sciencedirect.com/science/article/pii/S0048969724083220?via%3Dihub).
Thus, it is worth noting that in some study areas you could explore the potential affection of EUNIS habitats and/or 
saltmarsh and mudflat current affection and under a set of climate change scenarios. The following table is a summary
of the available affection in each study area:

| Study Area        | Physical Accounts     | Saltmarsh Evolution   |
| -------------     | --------------------- | --------------------- |
| Santander Coast   | ✅                    | ✅                   |
| North Sea         | ✅                    | ❌                   |
| Irish Sea         | ✅                    | ❌                   |
| Urdaibai Estuary  | ❌                    | ✅                   |
| Cadiz Bay         | ❌                    | ✅                   |                      
